'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("Role", [
      {
        role_name: 'superAdmin',
        role_description: 'Super Admin role',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_name: 'admin',
        role_description: 'Admin role',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_name: 'user',
        role_description: 'User role',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
    await queryInterface.bulkInsert("Permission", [
      {
        action: 'Get All Subscription',
        base_url: '/api/subscription',
        method: 'GET',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get Subscription By Id',
        base_url: '/api/subscription',
        method: 'GET',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Create Subscription',
        base_url: '/api/subscription',
        method: 'POST',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Update Subscription By Id',
        base_url: '/api/subscription',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Delete Subscription By Id',
        base_url: '/api/subscription',
        method: 'DELETE',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Restore Subscription By Id',
        base_url: '/api/subscription/restore',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get All Contract',
        base_url: '/api/contract',
        method: 'GET',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get Contract By Id',
        base_url: '/api/contract',
        method: 'GET',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Create Contract',
        base_url: '/api/contract',
        method: 'POST',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Update Contract By Id',
        base_url: '/api/contract',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Delete Contract By Id',
        base_url: '/api/contract',
        method: 'DELETE',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Restore Contract By Id',
        base_url: '/api/contract/restore',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },

      {
        action: 'User Signup',
        base_url: '/api/auth',
        method: 'POST',
        path: '/signup',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'User Login',
        base_url: '/api/auth',
        method: 'POST',
        path: '/login',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'User Logout',
        base_url: '/api/auth',
        method: 'POST',
        path: '/logout',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get Current User',
        base_url: '/api/auth',
        method: 'GET',
        path: '/me',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Reset Password',
        base_url: '/api/auth',
        method: 'POST',
        path: '/password/reset',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Update Kick By Id',
        base_url: '/api/kick',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get All Kick',
        base_url: '/api/kick',
        method: 'GET',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get Kick By Id',
        base_url: '/api/kick',
        method: 'GET',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Update Payment',
        base_url: '/api/payment',
        method: 'PUT',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get All Permission',
        base_url: '/api/permission',
        method: 'GET',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get Permission By Id',
        base_url: '/api/permission',
        method: 'GET',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Create Permission',
        base_url: '/api/permission',
        method: 'POST',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Update Permission By Id',
        base_url: '/api/permission',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Delete Permission By Id',
        base_url: '/api/permission',
        method: 'DELETE',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Restore Permission By Id',
        base_url: '/api/permission/restore',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get All Roles',
        base_url: '/api/role',
        method: 'GET',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get Role By Id',
        base_url: '/api/role',
        method: 'GET',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Create Role',
        base_url: '/api/role',
        method: 'POST',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Update Role By Id',
        base_url: '/api/role',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Delete Role By Id',
        base_url: '/api/role',
        method: 'DELETE',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Restore Role By Id',
        base_url: '/api/role/restore',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get Role Permission',
        base_url: '/api/role-permission',
        method: 'GET',
        path: '/:roleId',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Update Role Permission',
        base_url: '/api/role-permission',
        method: 'PUT',
        path: '/:roleId',
        created_at: new Date(),
        updated_at: new Date(),
      },

      {
        action: 'Get All Users',
        base_url: '/api/user',
        method: 'GET',
        path: '/',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get User By Id',
        base_url: '/api/user',
        method: 'GET',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Update User By Id',
        base_url: '/api/user',
        method: 'PUT',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Delete User By Id',
        base_url: '/api/user',
        method: 'DELETE',
        path: '/id',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get User Subscription',
        base_url: '/api/user',
        method: 'GET',
        path: '/subscription',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get User Kick',
        base_url: '/api/user',
        method: 'GET',
        path: '/kick',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get User Contract',
        base_url: '/api/user',
        method: 'GET',
        path: '/contract',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Get User Payment',
        base_url: '/api/user',
        method: 'GET',
        path: '/payment',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Create Kick',
        base_url: '/api/user',
        method: 'POST',
        path: '/kick',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        action: 'Add User Subscription',
        base_url: '/api/user',
        method: 'POST',
        path: '/buy-subscription',
        created_at: new Date(),
        updated_at: new Date(),
      },

    ]);
    await queryInterface.bulkInsert('User', [
      {
        first_name: "SuperAdmin",
        last_name: "User",
        email: "superadmin@gmail.com",
        role_id: 1,
        password: "$2b$10$uUKG4e0k980H6HZFKwxPaOk/z0sDSD2uskTrliMprtX/LKXZCPRw2",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: "Admin",
        last_name: "User",
        email: "admin@gmail.com",
        role_id: 2,
        password: "$2b$10$uUKG4e0k980H6HZFKwxPaOk/z0sDSD2uskTrliMprtX/LKXZCPRw2",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: "User",
        last_name: "User",
        email: "user@gmail.com",
        role_id: 3,
        password: "$2b$10$uUKG4e0k980H6HZFKwxPaOk/z0sDSD2uskTrliMprtX/LKXZCPRw2",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
    await queryInterface.bulkInsert('RolePermission', [
      {
        role_id: 1,
        permission_id: 22,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 23,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 24,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 25,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 26,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 27,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 28,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 29,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 30,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 31,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 32,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 33,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 34,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 1,
        permission_id: 35,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 6,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 7,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 8,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 9,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 10,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 11,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 12,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 18,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 19,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 20,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 21,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 36,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 37,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 38,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 2,
        permission_id: 39,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 3,
        permission_id: 40,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 3,
        permission_id: 41,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 3,
        permission_id: 42,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 3,
        permission_id: 43,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 3,
        permission_id: 44,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        role_id: 3,
        permission_id: 45,
        created_at: new Date(),
        updated_at: new Date(),
      },


    ])
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.dropTable("Role", {});
    await queryInterface.dropTable("Permission", {});
    await queryInterface.dropTable("User", {});
  }
};
